apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rancher-volume
  namespace: cattle-system
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=3
  accessModes:
    - ReadWriteMany
  nfs:
    server: my.server
    path: /home/pj/nfs/public/rancher
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rancher-claim
  namespace: cattle-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 128Mi