#!/bin/bash

kubeprovision()
{
  NODE=$1
  # check if we have k8s profile or create one
  lxc profile list | grep -qo k8s || (lxc profile create k8s && cat k8s-profile-config | lxc profile edit k8s)
  echo

  echo "==> Bringing up $NODE"
  lxc launch ubuntu:22.04 $NODE --profile k8s
  sleep 30
  lxc config device add $NODE eth0 nic nictype=bridged parent=br0 name=eth0
  echo "==> Running provisioner script on $NODE"
  lxc config device add $NODE kvm unix-char source=/dev/kvm
  lxc config device add $NODE vhost-net unix-char source=/dev/vhost-net
  lxc config device add $NODE vhost-vsock unix-char source=/dev/vhost-vsock
  lxc config device add $NODE "kmsg" unix-char source="/dev/kmsg" path="/dev/kmsg"
  lxc exec $NODE mkdir /etc/containerd
  lxc file push ./config.toml $NODE/etc/containerd/config.toml
  lxc file push ./crictl.yaml $NODE/etc/crictl.yaml
  lxc exec $NODE mkdir /run/flannel
  lxc file push ./flannel_subnet.env $NODE/run/flannel/subnet.env
  cat bootstrap-kube.sh | lxc exec $NODE bash
  echo

  echo "==> Running configure script on $NODE"
  # lxc file push joincluster.sh $node/joincluster.sh
  cat configure-worker.sh | lxc exec $NODE bash
  echo

  echo "==> All done. Manually join the cluster by running the command `kubeadm token create --print-join-command` in master."
}

case "$1" in
  provision)
    echo -e "\nProvisioning Kubernetes Cluster...\n"
    kubeprovision "$2"
    ;;
esac
