apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-list
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.10-192.168.0.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool-advert
  namespace: metallb-system
# spec:
#   ipAddressPools:
#   - pool-list